# Generated by Django 4.0.2 on 2022-10-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describtion', models.TextField()),
                ('langAndTool', models.CharField(choices=[('React', 'React'), ('Django', 'React'), ('Next', 'React')], max_length=100)),
            ],
        ),
    ]
