# Generated by Django 4.0.2 on 2022-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0002_projects_images_alter_projects_describtion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='images',
            field=models.ImageField(default='', upload_to='projects/'),
        ),
    ]
