# Generated by Django 4.1.3 on 2022-11-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0004_remove_projects_images_projectimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('images', models.ImageField(default='', upload_to='languge/')),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='langAndTool',
        ),
    ]
