# Generated by Django 4.1.3 on 2022-11-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0005_languge_remove_projects_langandtool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languge',
            old_name='title',
            new_name='language',
        ),
    ]
