# Generated by Django 4.1.3 on 2022-11-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0006_rename_title_languge_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='LangugeAndTool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApi.languge'),
        ),
    ]
