# Generated by Django 4.1.3 on 2022-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0007_projects_langugeandtool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='LangugeAndTool',
        ),
        migrations.AddField(
            model_name='projects',
            name='languageAndTool',
            field=models.ManyToManyField(blank=True, null=True, to='MainApi.languge'),
        ),
    ]
