# Generated by Django 4.1.3 on 2022-11-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0009_remove_projects_languageandtool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='LangugeAndTool',
        ),
        migrations.AddField(
            model_name='projects',
            name='LangugeAndTool',
            field=models.ManyToManyField(blank=True, null=True, to='MainApi.languge'),
        ),
    ]
