# Generated by Django 4.1.3 on 2022-11-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0010_remove_projects_langugeandtool_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languge',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='LangugeAndTool',
            new_name='languageAndTool',
        ),
    ]
