# Generated by Django 4.1.3 on 2022-11-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0011_rename_languge_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='languageAndTool',
        ),
        migrations.AddField(
            model_name='projects',
            name='languageAndTool',
            field=models.CharField(choices=[('React', 'React'), ('Next.js', 'Next.js'), ('Django', 'Django')], default='', max_length=100),
        ),
    ]
