# Generated by Django 4.1.3 on 2022-12-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0012_remove_projects_languageandtool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='languageAndTool',
        ),
        migrations.AddField(
            model_name='projects',
            name='languageAndTool',
            field=models.ManyToManyField(to='MainApi.language'),
        ),
    ]
