# Generated by Django 4.1.3 on 2022-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0013_remove_projects_languageandtool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(null=True, upload_to='projects/')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='languageAndTool',
            field=models.ManyToManyField(related_name='tools', to='MainApi.language'),
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(related_name='image', to='MainApi.image'),
        ),
    ]
