# Generated by Django 4.1.3 on 2022-12-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0014_image_alter_projects_languageandtool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='images', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(related_name='pics', to='MainApi.image'),
        ),
    ]
