# Generated by Django 4.1.3 on 2022-12-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0016_contact_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.FileField(default='', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(default='', related_name='project_images', to='MainApi.image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='languageAndTool',
            field=models.ManyToManyField(default='', related_name='tools', to='MainApi.language'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('image', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='MainApi.image')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('detail', models.TextField(default='')),
                ('images', models.ManyToManyField(default='', related_name='service_images', to='MainApi.image')),
            ],
        ),
    ]
