# Generated by Django 4.1.3 on 2022-12-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApi', '0017_project_git_link_project_project_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='git_link',
            new_name='workflow_link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(default='', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='MainApi.language'),
        ),
    ]
